// Pre-built event templates for common Indian event types

export const SYSTEM_TEMPLATES = [
  {
    name: "Grand Indian Wedding",
    event_type: "wedding" as const,
    sub_events: [
      { name: "Mehendi Ceremony", type: "mehendi" as const },
      { name: "Haldi Ceremony", type: "haldi" as const },
      { name: "Sangeet Night", type: "sangeet" as const },
      { name: "Wedding Ceremony", type: "wedding" as const },
      { name: "Reception", type: "reception" as const },
      { name: "Vidaai", type: "vidaai" as const },
    ],
    tasks: [
      { title: "Finalize venue booking", priority: "high" as const, days_before: 120 },
      { title: "Book photographer & videographer", priority: "high" as const, days_before: 90 },
      { title: "Finalize decorator & theme", priority: "high" as const, days_before: 90 },
      { title: "Book caterer & finalize menu", priority: "high" as const, days_before: 60 },
      { title: "Order wedding invitations", priority: "medium" as const, days_before: 60 },
      { title: "Book makeup artist", priority: "medium" as const, days_before: 45 },
      { title: "Arrange transport & baraat", priority: "medium" as const, days_before: 45 },
      { title: "Book DJ/music band", priority: "medium" as const, days_before: 30 },
      { title: "Book pandit/priest", priority: "high" as const, days_before: 30 },
      { title: "Finalize guest list & seating", priority: "high" as const, days_before: 21 },
      { title: "Arrange fireworks", priority: "low" as const, days_before: 14 },
      { title: "Final vendor payments & confirmations", priority: "high" as const, days_before: 7 },
      { title: "Send WhatsApp reminders to guests", priority: "medium" as const, days_before: 5 },
      { title: "Final venue walk-through", priority: "high" as const, days_before: 3 },
      { title: "Distribute welcome gifts", priority: "low" as const, days_before: 1 },
    ],
    vendor_categories: [
      "venue", "decorator", "caterer", "photographer", "videographer",
      "makeup", "dj", "pandit", "florist", "lighting", "tent_house",
      "transport", "invitation", "fireworks", "gifting",
    ],
    budget_split: {
      venue: 25, decorator: 15, caterer: 20, photographer: 8,
      videographer: 5, makeup: 5, dj: 3, pandit: 2,
      florist: 4, lighting: 4, transport: 3, invitation: 3,
      fireworks: 1, gifting: 2,
    },
  },
  {
    name: "Intimate Wedding",
    event_type: "wedding" as const,
    sub_events: [
      { name: "Haldi & Mehendi", type: "haldi" as const },
      { name: "Wedding Ceremony", type: "wedding" as const },
      { name: "Reception Dinner", type: "reception" as const },
    ],
    tasks: [
      { title: "Book intimate venue", priority: "high" as const, days_before: 60 },
      { title: "Book photographer", priority: "high" as const, days_before: 45 },
      { title: "Finalize caterer (50-100 pax)", priority: "high" as const, days_before: 30 },
      { title: "Book decorator for minimal decor", priority: "medium" as const, days_before: 30 },
      { title: "Send digital invitations", priority: "medium" as const, days_before: 21 },
      { title: "Book makeup artist", priority: "medium" as const, days_before: 21 },
      { title: "Finalize playlist/DJ", priority: "low" as const, days_before: 14 },
      { title: "Final confirmations", priority: "high" as const, days_before: 3 },
    ],
    vendor_categories: ["venue", "decorator", "caterer", "photographer", "makeup", "dj", "pandit", "florist"],
    budget_split: {
      venue: 30, caterer: 25, decorator: 15, photographer: 10,
      makeup: 5, dj: 3, pandit: 2, florist: 5, other: 5,
    },
  },
  {
    name: "Engagement Ceremony",
    event_type: "engagement" as const,
    sub_events: [
      { name: "Ring Ceremony", type: "engagement" as const },
      { name: "Cocktail & Dinner", type: "cocktail" as const },
    ],
    tasks: [
      { title: "Book venue/banquet hall", priority: "high" as const, days_before: 45 },
      { title: "Book photographer", priority: "high" as const, days_before: 30 },
      { title: "Order ring ceremony stage decor", priority: "medium" as const, days_before: 21 },
      { title: "Finalize menu", priority: "high" as const, days_before: 14 },
      { title: "Send invitations", priority: "medium" as const, days_before: 14 },
      { title: "Book makeup artist", priority: "medium" as const, days_before: 14 },
      { title: "Arrange music/DJ", priority: "low" as const, days_before: 7 },
    ],
    vendor_categories: ["venue", "decorator", "caterer", "photographer", "makeup", "dj", "florist"],
    budget_split: {
      venue: 30, caterer: 25, decorator: 15, photographer: 10,
      makeup: 5, dj: 5, florist: 5, other: 5,
    },
  },
  {
    name: "Corporate Event",
    event_type: "corporate" as const,
    sub_events: [
      { name: "Main Event", type: "other" as const },
    ],
    tasks: [
      { title: "Define event objective & agenda", priority: "high" as const, days_before: 60 },
      { title: "Book venue with AV setup", priority: "high" as const, days_before: 45 },
      { title: "Confirm speakers/presenters", priority: "high" as const, days_before: 30 },
      { title: "Arrange catering & refreshments", priority: "medium" as const, days_before: 21 },
      { title: "Design event branding & standees", priority: "medium" as const, days_before: 21 },
      { title: "Send corporate invitations", priority: "high" as const, days_before: 14 },
      { title: "Arrange transport for VIPs", priority: "medium" as const, days_before: 7 },
      { title: "Test AV equipment & run-through", priority: "high" as const, days_before: 2 },
      { title: "Print name badges & materials", priority: "medium" as const, days_before: 2 },
    ],
    vendor_categories: ["venue", "caterer", "decorator", "lighting", "anchor", "transport", "entertainment"],
    budget_split: {
      venue: 35, caterer: 20, decorator: 10, lighting: 10,
      anchor: 5, transport: 5, entertainment: 5, other: 10,
    },
  },
  {
    name: "Birthday Party",
    event_type: "birthday" as const,
    sub_events: [
      { name: "Birthday Party", type: "other" as const },
    ],
    tasks: [
      { title: "Book venue or decide home party", priority: "high" as const, days_before: 30 },
      { title: "Decide party theme", priority: "medium" as const, days_before: 21 },
      { title: "Order cake", priority: "high" as const, days_before: 7 },
      { title: "Arrange decorations & balloons", priority: "medium" as const, days_before: 7 },
      { title: "Finalize menu/catering", priority: "high" as const, days_before: 7 },
      { title: "Send invitations", priority: "medium" as const, days_before: 14 },
      { title: "Arrange entertainment/games", priority: "low" as const, days_before: 5 },
      { title: "Buy return gifts", priority: "low" as const, days_before: 3 },
    ],
    vendor_categories: ["venue", "decorator", "caterer", "photographer", "entertainment", "gifting"],
    budget_split: {
      venue: 25, caterer: 25, decorator: 20, photographer: 10,
      entertainment: 10, gifting: 10,
    },
  },
  {
    name: "Reception Only",
    event_type: "reception" as const,
    sub_events: [
      { name: "Reception Ceremony", type: "reception" as const },
    ],
    tasks: [
      { title: "Book banquet hall", priority: "high" as const, days_before: 45 },
      { title: "Finalize stage & entry decor", priority: "high" as const, days_before: 30 },
      { title: "Book photographer & videographer", priority: "high" as const, days_before: 30 },
      { title: "Finalize menu", priority: "high" as const, days_before: 21 },
      { title: "Book DJ/orchestra", priority: "medium" as const, days_before: 14 },
      { title: "Print & send invitations", priority: "medium" as const, days_before: 14 },
      { title: "Arrange valet parking", priority: "low" as const, days_before: 7 },
      { title: "Final walk-through with venue", priority: "high" as const, days_before: 2 },
    ],
    vendor_categories: ["venue", "decorator", "caterer", "photographer", "videographer", "dj", "lighting", "florist"],
    budget_split: {
      venue: 30, caterer: 25, decorator: 15, photographer: 8,
      videographer: 5, dj: 5, lighting: 5, florist: 7,
    },
  },
];
