import { jsPDF } from "jspdf";

type InvoiceData = {
  invoice_number: string;
  client_name: string;
  client_phone?: string | null;
  client_email?: string | null;
  items: { description: string; category?: string; amount: number }[];
  subtotal: number;
  tax_percent: number;
  tax_amount: number;
  total: number;
  amount_paid: number;
  due_date?: string | null;
  notes?: string | null;
  created_at: string;
  agency_name?: string;
  agency_phone?: string;
};

type ProposalData = {
  proposal_number: string;
  client_name: string;
  client_phone?: string | null;
  client_email?: string | null;
  event_type?: string;
  event_date?: string | null;
  venue?: string | null;
  items: { description: string; category?: string; amount: number }[];
  subtotal: number;
  discount_percent: number;
  discount_amount: number;
  tax_percent: number;
  tax_amount: number;
  total: number;
  terms_and_conditions?: string | null;
  valid_until?: string | null;
  created_at: string;
  agency_name?: string;
  agency_phone?: string;
};

function formatINR(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

function formatDateStr(dateString: string): string {
  return new Date(dateString).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function addHeader(doc: jsPDF, title: string, number: string, agencyName?: string) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(agencyName || "EventKhata", 20, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Event Management", 20, 28);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 190, 18, { align: "right" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(number, 190, 26, { align: "right" });

  doc.setTextColor(0, 0, 0);
}

function addFooter(doc: jsPDF) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageHeight - 20, 210, 20, "F");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by EventKhata - Digital Bahi Khata for Event Planners", 105, pageHeight - 10, { align: "center" });
  doc.setTextColor(0, 0, 0);
}

export function generateInvoicePDF(data: InvoiceData): jsPDF {
  const doc = new jsPDF();

  addHeader(doc, "INVOICE", data.invoice_number, data.agency_name);

  let y = 52;

  // Client info + dates
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(100, 116, 139);
  doc.text("BILL TO", 20, y);
  doc.text("DETAILS", 130, y);
  y += 6;

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(data.client_name, 20, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Date: ${formatDateStr(data.created_at)}`, 130, y);
  y += 5;

  if (data.client_phone) {
    doc.text(data.client_phone, 20, y);
    y += 5;
  }
  if (data.client_email) {
    doc.text(data.client_email, 20, y);
  }
  if (data.due_date) {
    doc.text(`Due: ${formatDateStr(data.due_date)}`, 130, y - (data.client_phone ? 0 : 5) + 5);
  }

  y = Math.max(y, 72) + 10;

  // Items table header
  doc.setFillColor(241, 245, 249);
  doc.rect(20, y - 4, 170, 8, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(71, 85, 105);
  doc.text("#", 24, y);
  doc.text("Description", 32, y);
  doc.text("Amount", 186, y, { align: "right" });
  y += 8;

  // Items
  doc.setFont("helvetica", "normal");
  doc.setTextColor(15, 23, 42);
  (data.items || []).forEach((item, i) => {
    if (y > 250) {
      doc.addPage();
      addFooter(doc);
      y = 20;
    }
    doc.setFontSize(10);
    doc.text(`${i + 1}`, 24, y);
    const desc = item.category ? `${item.description} (${item.category})` : item.description;
    doc.text(desc.substring(0, 60), 32, y);
    doc.text(formatINR(item.amount), 186, y, { align: "right" });
    doc.setDrawColor(226, 232, 240);
    doc.line(20, y + 3, 190, y + 3);
    y += 8;
  });

  y += 4;

  // Totals
  const totalsX = 130;
  doc.setFontSize(10);
  doc.text("Subtotal", totalsX, y);
  doc.text(formatINR(data.subtotal), 186, y, { align: "right" });
  y += 6;

  if (data.tax_percent > 0) {
    doc.text(`Tax (${data.tax_percent}%)`, totalsX, y);
    doc.text(formatINR(data.tax_amount), 186, y, { align: "right" });
    y += 6;
  }

  doc.setDrawColor(15, 23, 42);
  doc.line(totalsX, y - 2, 190, y - 2);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("TOTAL", totalsX, y + 3);
  doc.text(formatINR(data.total), 186, y + 3, { align: "right" });
  y += 10;

  if (data.amount_paid > 0 && data.amount_paid < data.total) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(16, 185, 129);
    doc.text("Amount Paid", totalsX, y);
    doc.text(formatINR(data.amount_paid), 186, y, { align: "right" });
    y += 6;
    doc.setTextColor(239, 68, 68);
    doc.setFont("helvetica", "bold");
    doc.text("Balance Due", totalsX, y);
    doc.text(formatINR(data.total - data.amount_paid), 186, y, { align: "right" });
    doc.setTextColor(0, 0, 0);
  }

  if (data.notes) {
    y += 12;
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 116, 139);
    doc.text("NOTES", 20, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    const lines = doc.splitTextToSize(data.notes, 170);
    doc.text(lines, 20, y);
  }

  addFooter(doc);
  return doc;
}

export function generateProposalPDF(data: ProposalData): jsPDF {
  const doc = new jsPDF();

  addHeader(doc, "PROPOSAL", data.proposal_number, data.agency_name);

  let y = 52;

  // Client info
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(100, 116, 139);
  doc.text("PREPARED FOR", 20, y);
  doc.text("EVENT DETAILS", 130, y);
  y += 6;

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(data.client_name, 20, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  if (data.event_type) {
    doc.text(`Type: ${data.event_type.charAt(0).toUpperCase() + data.event_type.slice(1)}`, 130, y);
  }
  y += 5;

  if (data.client_phone) {
    doc.text(data.client_phone, 20, y);
  }
  if (data.event_date) {
    doc.text(`Date: ${formatDateStr(data.event_date)}`, 130, y);
  }
  y += 5;

  if (data.client_email) {
    doc.text(data.client_email, 20, y);
  }
  if (data.venue) {
    doc.text(`Venue: ${data.venue.substring(0, 30)}`, 130, y);
  }

  y += 10;

  if (data.valid_until) {
    doc.setFontSize(9);
    doc.setTextColor(245, 158, 11);
    doc.text(`Valid until: ${formatDateStr(data.valid_until)}`, 20, y);
    doc.setTextColor(0, 0, 0);
    y += 8;
  }

  // Items table header
  doc.setFillColor(241, 245, 249);
  doc.rect(20, y - 4, 170, 8, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(71, 85, 105);
  doc.text("#", 24, y);
  doc.text("Description", 32, y);
  doc.text("Category", 120, y);
  doc.text("Amount", 186, y, { align: "right" });
  y += 8;

  // Items
  doc.setFont("helvetica", "normal");
  doc.setTextColor(15, 23, 42);
  (data.items || []).forEach((item, i) => {
    if (y > 240) {
      doc.addPage();
      addFooter(doc);
      y = 20;
    }
    doc.setFontSize(10);
    doc.text(`${i + 1}`, 24, y);
    doc.text(item.description.substring(0, 45), 32, y);
    if (item.category) doc.text(item.category.substring(0, 15), 120, y);
    doc.text(formatINR(item.amount), 186, y, { align: "right" });
    doc.setDrawColor(226, 232, 240);
    doc.line(20, y + 3, 190, y + 3);
    y += 8;
  });

  y += 4;

  // Totals
  const totalsX = 130;
  doc.setFontSize(10);
  doc.text("Subtotal", totalsX, y);
  doc.text(formatINR(data.subtotal), 186, y, { align: "right" });
  y += 6;

  if (data.discount_percent > 0 || data.discount_amount > 0) {
    doc.setTextColor(16, 185, 129);
    doc.text(`Discount (${data.discount_percent}%)`, totalsX, y);
    doc.text(`-${formatINR(data.discount_amount)}`, 186, y, { align: "right" });
    doc.setTextColor(0, 0, 0);
    y += 6;
  }

  if (data.tax_percent > 0) {
    doc.text(`Tax (${data.tax_percent}%)`, totalsX, y);
    doc.text(formatINR(data.tax_amount), 186, y, { align: "right" });
    y += 6;
  }

  doc.setDrawColor(15, 23, 42);
  doc.line(totalsX, y - 2, 190, y - 2);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("TOTAL", totalsX, y + 4);
  doc.text(formatINR(data.total), 186, y + 4, { align: "right" });
  y += 14;

  // Terms
  if (data.terms_and_conditions) {
    if (y > 220) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 116, 139);
    doc.text("TERMS & CONDITIONS", 20, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    doc.setFontSize(8);
    const lines = doc.splitTextToSize(data.terms_and_conditions, 170);
    doc.text(lines.slice(0, 20), 20, y);
  }

  addFooter(doc);
  return doc;
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename);
}

export function getPDFBlob(doc: jsPDF): Blob {
  return doc.output("blob");
}

type ReceiptData = {
  event_name: string;
  vendor_name: string;
  vendor_category?: string;
  amount: number;
  payment_mode: string;
  txn_type: string;
  reference_number?: string | null;
  notes?: string | null;
  recorded_at: string;
  agency_name?: string;
};

export function generatePaymentReceiptPDF(data: ReceiptData): jsPDF {
  const doc = new jsPDF({ format: [105, 148] }); // A6 size

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 105, 25, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(data.agency_name || "EventKhata", 52.5, 12, { align: "center" });
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("PAYMENT RECEIPT", 52.5, 19, { align: "center" });

  doc.setTextColor(0, 0, 0);
  let y = 35;

  const labelX = 10;
  const valueX = 48;

  function addRow(label: string, value: string) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(label, labelX, y);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text(value, valueX, y);
    y += 7;
  }

  addRow("Date", formatDateStr(data.recorded_at));
  addRow("Event", data.event_name.substring(0, 30));
  addRow("Vendor", data.vendor_name.substring(0, 30));
  if (data.vendor_category) addRow("Category", data.vendor_category);
  addRow("Type", data.txn_type);
  addRow("Mode", data.payment_mode);
  if (data.reference_number) addRow("Reference", data.reference_number);

  y += 5;
  doc.setDrawColor(226, 232, 240);
  doc.line(10, y, 95, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text("Amount", labelX, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(16, 185, 129);
  doc.text(formatINR(data.amount), valueX, y);

  if (data.notes) {
    y += 12;
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text("Notes:", labelX, y);
    y += 4;
    doc.setTextColor(71, 85, 105);
    const lines = doc.splitTextToSize(data.notes, 80);
    doc.text(lines.slice(0, 3), labelX, y);
  }

  // Footer
  doc.setFontSize(6);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by EventKhata", 52.5, 140, { align: "center" });

  return doc;
}
